In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("/content/goal15.forest_shares.csv")
df.head()

iso3c  forests_2000  forests_2020  trend
0   AFG           1.9           1.9    0.0
1   ALB          28.1          28.8    2.5
2   DZA           0.7           0.8   14.3
3   ASM          88.7          85.7   -3.4
4   AND          34.0          34.0    0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   iso3c         237 non-null    object 
 1   forests_2000  237 non-null    float64
 2   forests_2020  237 non-null    float64
 3   trend         227 non-null    float64
dtypes: float64(3), object(1)
memory usage: 7.5+ KB


In [5]:
df.describe()

forests_2000  forests_2020       trend
count    237.000000    237.000000  227.000000
mean      32.255274     31.585654    0.104846
std       25.366225     24.744673   16.863427
min        0.000000      0.000000 -100.000000
25%        9.900000     10.400000   -5.500000
50%       30.300000     30.300000    0.000000
75%       50.900000     49.800000    4.650000
max       98.300000     97.400000   86.200000

In [6]:
df.isnull().sum()

iso3c            0
forests_2000     0
forests_2020     0
trend           10
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["iso3c"] = label_encoder.fit_transform(df["iso3c"])

In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["trend"] = label_encoder.fit_transform(df["trend"])

In [10]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=["trend"])  # Features
y = df["trend"]  # Target variable

In [11]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)


In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

LogisticRegression()

In [14]:
ypred = model.predict(xtest)

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)
class_report = classification_report(ytest, ypred)

# Print results
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Model Accuracy: 0.125
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Classification Report:
               precision    recall  f1-score   support

           2       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          32       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          36       0.00      0.00      0.00         1
          39       0.00      0.00      0.00         1
          43       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         1
          51       0.00      0.00      0.00         1
          53       0.00      0.00      0.00         1
          60       0.00      0.00      0.00         1
    

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_